version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-233-123.compute-1.amazonaws.com
            database: d3sfhkg6nt7h8s
            schema: public
            user: ojiqscwzatqznf
            password: 60d1ecdf89859db3955e3340b126b74c7aa801d8ca96593ac72cab10894efdeb
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
